name: "Build application"
on: [push]
jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: 'stable'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt flet markdownify

            - name: Flet build windows
              run: |
                flutter config --no-analytics
                flet build windows --verbose --no-rich-output
            
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: windows-build-artifact
                path: build/windows
                if-no-files-found: warn
                overwrite: false